### ISSUE TITLE
Duplicate Sample 5 printouts

### ISSUE THREAD

**Issue by ChosunOne** [ivan-vasilev/Python-Deep-Learning-SE#2]
https://github.com/ivan-vasilev/Python-Deep-Learning-SE/blob/53ee58399c2352e12265a82be274e6ba61f33cce/ch07/language%20model/model.py#L210

There is a duplicate of "Sample 5" on line 210.  It should be changed to "Sample 6".

**Comment by ivan-vasilev** [comment]
Thank you for your contribution. The issue has been fixed now.
